# Generated by Django 5.2 on 2025-04-24 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'FIO',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=200)),
                ('fio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fio')),
            ],
            options={
                'db_table': 'job',
            },
        ),
    ]
