version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - django.env
    volumes:
      - static_volume:/app/static

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
    depends_on:
      - web

volumes:
  pg_data:
  static_volume: