FROM nginx:alpine

RUN rm -rf \
/etc/nginx/conf.d/default.conf \
/usr/share/nginx/html/* \
/var/cache/apk/* \
/tmp/*

COPY nginx.conf /etc/nginx/conf.d/default.conf


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]